In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

/Users/freestylebk/anaconda/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


## 1. csv 파일로 만들기

In [51]:
with open("bank-additional-full.csv","r") as fp:
    raw = fp.read().replace('"','')
    
    raw_split = []
    lines = raw.split("\n")
    title = lines[0].split(";")
    
    for line in lines[1:]:
        elements = line.split(";")
        ele_dict = {}
        
        for i in range(len(elements)):
            ele_dict[title[i]] = elements[i]
        
        raw_split.append(ele_dict)

In [53]:
raw_split[:2]

[{'age': '56',
  'campaign': '1',
  'cons.conf.idx': '-36.4',
  'cons.price.idx': '93.994',
  'contact': 'telephone',
  'day_of_week': 'mon',
  'default': 'no',
  'duration': '261',
  'education': 'basic.4y',
  'emp.var.rate': '1.1',
  'euribor3m': '4.857',
  'housing': 'no',
  'job': 'housemaid',
  'loan': 'no',
  'marital': 'married',
  'month': 'may',
  'nr.employed': '5191',
  'pdays': '999',
  'poutcome': 'nonexistent',
  'previous': '0',
  'y': 'no'},
 {'age': '57',
  'campaign': '1',
  'cons.conf.idx': '-36.4',
  'cons.price.idx': '93.994',
  'contact': 'telephone',
  'day_of_week': 'mon',
  'default': 'unknown',
  'duration': '149',
  'education': 'high.school',
  'emp.var.rate': '1.1',
  'euribor3m': '4.857',
  'housing': 'no',
  'job': 'services',
  'loan': 'no',
  'marital': 'married',
  'month': 'may',
  'nr.employed': '5191',
  'pdays': '999',
  'poutcome': 'nonexistent',
  'previous': '0',
  'y': 'no'}]

In [55]:
len(raw_split)
# 맨 마지막 행이 empty로 들어가 있어서 카운팅이 +1 됨. 최종적으로 마지막 행 지우기

41189

In [60]:
raw_split = raw_split[:-1]

In [62]:
with open("bank-info-preprocessing.csv", 'w') as fw:
    for t in title:
        fw.write(t+",")
    
    fw.write("\n")
    
    for e in raw_split:
        for t in title:
            fw.write(e[t]+",")
        fw.write("\n")

## 2. pandas로 데이터 자세히 들여다보기

In [40]:
xy = pd.read_csv("bank-info-preprocessing.csv")

In [41]:
xy.head()

age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone   
1   57   services  married  high.school  unknown      no   no  telephone   
2   37   services  married  high.school       no     yes   no  telephone   
3   40     admin.  married     basic.6y       no      no   no  telephone   
4   56   services  married  high.school       no      no  yes  telephone   

  month day_of_week     ...       pdays  previous     poutcome  emp.var.rate  \
0   may         mon     ...         999         0  nonexistent           1.1   
1   may         mon     ...         999         0  nonexistent           1.1   
2   may         mon     ...         999         0  nonexistent           1.1   
3   may         mon     ...         999         0  nonexistent           1.1   
4   may         mon     ...         999         0  nonexistent           1.1   

  cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  Unnamed: 21  
0         93.994          -36.4      4.857       5191.0  no          NaN  
1         93.994          -36.4      4.857       5191.0  no          NaN  
2         93.994          -36.4      4.857       5191.0  no          NaN  
3         93.994          -36.4      4.857       5191.0  no          NaN  
4         93.994          -36.4      4.857       5191.0  no          NaN  

[5 rows x 22 columns]

In [42]:
xy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 22 columns):
age               41188 non-null int64
job               41188 non-null object
marital           41188 non-null object
education         41188 non-null object
default           41188 non-null object
housing           41188 non-null object
loan              41188 non-null object
contact           41188 non-null object
month             41188 non-null object
day_of_week       41188 non-null object
duration          41188 non-null int64
campaign          41188 non-null int64
pdays             41188 non-null int64
previous          41188 non-null int64
poutcome          41188 non-null object
emp.var.rate      41188 non-null float64
cons.price.idx    41188 non-null float64
cons.conf.idx     41188 non-null float64
euribor3m         41188 non-null float64
nr.employed       41188 non-null float64
y                 41188 non-null object
Unnamed: 21       0 non-null float64
dtypes: float6

In [43]:
xy["job"].value_counts()

admin.           10422
blue-collar       9254
technician        6743
services          3969
management        2924
retired           1720
entrepreneur      1456
self-employed     1421
housemaid         1060
unemployed        1014
student            875
unknown            330
Name: job, dtype: int64

In [44]:
xy = xy.drop('Unnamed: 21', axis=1)
# 왜 생겼는지 모를 'Unnamed: 21' 열을 삭제

In [45]:
xy = xy.drop('duration', axis=1)
xy = xy.drop('pdays', axis=1)
# 데이터가 불완전하거나 가공이 필요한 경우, 삭제

In [46]:
xy.head()

age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone   
1   57   services  married  high.school  unknown      no   no  telephone   
2   37   services  married  high.school       no     yes   no  telephone   
3   40     admin.  married     basic.6y       no      no   no  telephone   
4   56   services  married  high.school       no      no  yes  telephone   

  month day_of_week  campaign  previous     poutcome  emp.var.rate  \
0   may         mon         1         0  nonexistent           1.1   
1   may         mon         1         0  nonexistent           1.1   
2   may         mon         1         0  nonexistent           1.1   
3   may         mon         1         0  nonexistent           1.1   
4   may         mon         1         0  nonexistent           1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0          93.994          -36.4      4.857       5191.0  no  
1          93.994          -36.4      4.857       5191.0  no  
2          93.994          -36.4      4.857       5191.0  no  
3          93.994          -36.4      4.857       5191.0  no  
4          93.994          -36.4      4.857       5191.0  no

In [47]:
from sklearn.preprocessing import LabelBinarizer
encoder = LabelBinarizer()
xy_catg2 = xy['marital']
xy_catg2_1hot = encoder.fit_transform(xy_catg2)

In [48]:
encoder.classes_

array(['divorced', 'married', 'single', 'unknown'], dtype='<U8')

In [49]:
xy_catg2_1hot

array([[0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       ...,
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0]])

In [50]:
xy['marital'] = xy_catg2_1hot.tolist()

In [210]:
xy.head()

age                                   job       marital  \
0   56  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]  [0, 1, 0, 0]   
1   57  [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]  [0, 1, 0, 0]   
2   37  [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]  [0, 1, 0, 0]   
3   40  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]  [0, 1, 0, 0]   
4   56  [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]  [0, 1, 0, 0]   

                  education    default    housing       loan contact  \
0  [1, 0, 0, 0, 0, 0, 0, 0]  [1, 0, 0]  [1, 0, 0]  [1, 0, 0]     [1]   
1  [0, 0, 0, 1, 0, 0, 0, 0]  [0, 1, 0]  [1, 0, 0]  [1, 0, 0]     [1]   
2  [0, 0, 0, 1, 0, 0, 0, 0]  [1, 0, 0]  [0, 0, 1]  [1, 0, 0]     [1]   
3  [0, 1, 0, 0, 0, 0, 0, 0]  [1, 0, 0]  [1, 0, 0]  [1, 0, 0]     [1]   
4  [0, 0, 0, 1, 0, 0, 0, 0]  [1, 0, 0]  [1, 0, 0]  [0, 0, 1]     [1]   

                            month      day_of_week  campaign  previous  \
0  [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]  [0, 1, 0, 0, 0]         1         0   
1  [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]  [0, 1, 0, 0, 0]         1         0   
2  [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]  [0, 1, 0, 0, 0]         1         0   
3  [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]  [0, 1, 0, 0, 0]         1         0   
4  [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]  [0, 1, 0, 0, 0]         1         0   

    poutcome  emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
0  [0, 1, 0]           1.1          93.994          -36.4      4.857   
1  [0, 1, 0]           1.1          93.994          -36.4      4.857   
2  [0, 1, 0]           1.1          93.994          -36.4      4.857   
3  [0, 1, 0]           1.1          93.994          -36.4      4.857   
4  [0, 1, 0]           1.1          93.994          -36.4      4.857   

   nr.employed    y  
0       5191.0  [0]  
1       5191.0  [0]  
2       5191.0  [0]  
3       5191.0  [0]  
4       5191.0  [0]

In [56]:
dftitle = xy.columns.tolist()

In [57]:
dftitle

['age',
 'job',
 'marital',
 'education',
 'default',
 'housing',
 'loan',
 'contact',
 'month',
 'day_of_week',
 'campaign',
 'previous',
 'poutcome',
 'emp.var.rate',
 'cons.price.idx',
 'cons.conf.idx',
 'euribor3m',
 'nr.employed',
 'y']

In [60]:
dftitle = [x for x in dftitle if x not in ['marital', 'age', 'campaign', 'previous', 'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed']]
# 'marital' 열은 test로 이미 변환했으니까 변환할 열들의 이름에서 제외시키기.
# one hot encoding이 필요없는 열들 제외시키기.

In [61]:
dftitle

['job',
 'education',
 'default',
 'housing',
 'loan',
 'contact',
 'month',
 'day_of_week',
 'poutcome',
 'y']

In [62]:
for t in dftitle:
    xy_catg2 = xy[t]
    xy_catg2_1hot = encoder.fit_transform(xy_catg2)
    xy[t] = xy_catg2_1hot.tolist()

In [218]:
xy[10034:10036]

age                                   job       marital  \
10034   36  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]  [0, 1, 0, 0]   
10035   38  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]  [0, 1, 0, 0]   

                      education    default    housing       loan contact  \
10034  [0, 1, 0, 0, 0, 0, 0, 0]  [1, 0, 0]  [0, 0, 1]  [1, 0, 0]     [1]   
10035  [0, 0, 0, 0, 0, 0, 1, 0]  [1, 0, 0]  [1, 0, 0]  [1, 0, 0]     [1]   

                                month      day_of_week  campaign  previous  \
10034  [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]  [0, 0, 1, 0, 0]         2         0   
10035  [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]  [0, 0, 1, 0, 0]         2         0   

        poutcome  emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
10034  [0, 1, 0]           1.4          94.465          -41.8      4.958   
10035  [0, 1, 0]           1.4          94.465          -41.8      4.958   

       nr.employed    y  
10034       5228.1  [1]  
10035       5228.1  [0]

In [230]:
xy_numeric = xy[:]

In [67]:
# scaler를 돌리기 전에 train set, test set을 나눠줘야 함. 나누기 전에 scale을 해버리면 scaling에 영향을 주기 때문.

In [68]:
from sklearn.model_selection import train_test_split

In [231]:
train_set_noscale, test_set_noscale = train_test_split(xy_numeric, test_size=0.2, random_state=42)

In [211]:
len(train_set_noscale)

32950

In [212]:
len(test_set_noscale)

8238

In [213]:
len(test_set_noscale)/(len(train_set_noscale)+len(test_set_noscale))

0.20000971156647568

In [232]:
train_set = train_set_noscale[:]

In [81]:
scale_title = [t for t in train_set.columns.tolist() if t not in dftitle]

In [84]:
scale_title = [t for t in scale_title if t not in ['marital']]

In [85]:
scale_title

['age',
 'campaign',
 'previous',
 'emp.var.rate',
 'cons.price.idx',
 'cons.conf.idx',
 'euribor3m',
 'nr.employed']

In [86]:
from sklearn.preprocessing import MinMaxScaler

In [96]:
scaler_title = ["scaler{0}".format(i) for i in range(len(scale_title))]

In [101]:
scaler_dic = {}
for i in range(len(scale_title)):
    scaler_dic[scaler_title[i]] = MinMaxScaler().fit(train_set[scale_title[i]])

/Users/freestylebk/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, _DataConversionWarning)
/Users/freestylebk/anaconda/lib/python3.6/site-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/freestylebk/anaconda/lib/python3.6/site-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/User

In [102]:
scaler_dic

{'scaler0': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'scaler1': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'scaler2': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'scaler3': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'scaler4': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'scaler5': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'scaler6': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'scaler7': MinMaxScaler(copy=True, feature_range=(0, 1))}

In [104]:
scaler_dic['scaler0'].scale_

0.012345679012345678

In [233]:
for i in range(len(scale_title)):
    train_set[scale_title[i]] = scaler_dic["scaler{0}".format(i)].transform(train_set[scale_title[i]])

/Users/freestylebk/anaconda/lib/python3.6/site-packages/sklearn/preprocessing/data.py:356: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/freestylebk/anaconda/lib/python3.6/site-packages/sklearn/preprocessing/data.py:356: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/freestylebk/anaconda/lib/python3.6/site-packages/sklearn/preprocessing/data.py:356: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.resha

In [234]:
train_set.head()

age                                   job       marital  \
12556  0.283951  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]  [0, 1, 0, 0]   
35451  0.172840  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]  [0, 1, 0, 0]   
30592  0.518519  [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]  [0, 1, 0, 0]   
17914  0.320988  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]  [1, 0, 0, 0]   
3315   0.271605  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 1, 0]   

                      education    default    housing       loan contact  \
12556  [0, 0, 1, 0, 0, 0, 0, 0]  [0, 1, 0]  [0, 0, 1]  [1, 0, 0]     [1]   
35451  [0, 0, 0, 0, 0, 0, 1, 0]  [1, 0, 0]  [1, 0, 0]  [1, 0, 0]     [0]   
30592  [1, 0, 0, 0, 0, 0, 0, 0]  [1, 0, 0]  [1, 0, 0]  [1, 0, 0]     [0]   
17914  [0, 0, 1, 0, 0, 0, 0, 0]  [1, 0, 0]  [0, 0, 1]  [1, 0, 0]     [0]   
3315   [0, 0, 0, 1, 0, 0, 0, 0]  [0, 1, 0]  [1, 0, 0]  [1, 0, 0]     [1]   

                                month      day_of_week  campaign  previous  \
12556  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0]  [0, 1, 0, 0, 0]  0.018182  0.000000   
35451  [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]  [0, 1, 0, 0, 0]  0.054545  0.000000   
30592  [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]  [0, 1, 0, 0, 0]  0.090909  0.142857   
17914  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 1, 0]  0.072727  0.000000   
3315   [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]  [0, 0, 1, 0, 0]  0.018182  0.000000   

        poutcome  emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
12556  [0, 1, 0]      1.000000        0.669135       0.338912   0.980730   
35451  [0, 1, 0]      0.333333        0.269680       0.192469   0.138291   
30592  [1, 0, 0]      0.333333        0.269680       0.192469   0.163228   
17914  [0, 1, 0]      1.000000        0.669135       0.338912   0.980957   
3315   [0, 1, 0]      0.937500        0.698753       0.602510   0.958059   

       nr.employed    y  
12556     1.000000  [0]  
35451     0.512287  [0]  
30592     0.512287  [0]  
17914     1.000000  [0]  
3315      0.859735  [0]

In [235]:
train_set['previous'].value_counts()

0.000000    28437
0.142857     3666
0.285714      598
0.428571      181
0.571429       50
0.714286       14
0.857143        3
1.000000        1
Name: previous, dtype: int64

In [171]:
train_set_a = train_set.values.tolist()
# pandas dataframe을 numpy array로 만들기

In [236]:
train_set_a = train_set['marital'].apply(lambda x: np.array(x))

In [237]:
train_set['marital'] = train_set_a

In [238]:
train_set.values

array([[0.2839506172839506, list([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        array([0, 1, 0, 0]), ..., 0.9807299931988211, 1.0, list([0])],
       [0.1728395061728395, list([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        array([0, 1, 0, 0]), ..., 0.13829063704375427, 0.512287334593573,
        list([0])],
       [0.5185185185185184, list([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
        array([0, 1, 0, 0]), ..., 0.1632282929041034, 0.512287334593573,
        list([0])],
       ...,
       [0.2222222222222222, list([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        array([0, 1, 0, 0]), ..., 0.027204715484017233,
        0.20378071833648193, list([1])],
       [0.2839506172839506, list([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]),
        array([0, 1, 0, 0]), ..., 0.9571525731126729, 0.8597353497164448,
        list([0])],
       [0.14814814814814814, list([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        array([0, 0, 1, 0]), ..., 0.9807299931988211, 1.0, list([0])]],
      dtype=object)

In [239]:
for t in dftitle:
    train_set[t] = train_set[t].apply(lambda x:np.array(x))

In [240]:
train_set.values

array([[0.2839506172839506, array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        array([0, 1, 0, 0]), ..., 0.9807299931988211, 1.0, array([0])],
       [0.1728395061728395, array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        array([0, 1, 0, 0]), ..., 0.13829063704375427, 0.512287334593573,
        array([0])],
       [0.5185185185185184, array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
        array([0, 1, 0, 0]), ..., 0.1632282929041034, 0.512287334593573,
        array([0])],
       ...,
       [0.2222222222222222, array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        array([0, 1, 0, 0]), ..., 0.027204715484017233,
        0.20378071833648193, array([1])],
       [0.2839506172839506, array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]),
        array([0, 1, 0, 0]), ..., 0.9571525731126729, 0.8597353497164448,
        array([0])],
       [0.14814814814814814, array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        array([0, 0, 1, 0]), ..., 0.9807299931988211, 1.0, array([0])]],
      dtype=object)

In [241]:
x_train = train_set.values[:,0:-1]
y_train = train_set.values[:,[-1]]

In [252]:
y_train.shape

(32950, 1)

In [253]:
x_train.shape

(32950, 18)

In [275]:
x_train

array([[0.2839506172839506, array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        array([0, 1, 0, 0]), ..., 0.3389121338912131, 0.9807299931988211,
        1.0],
       [0.1728395061728395, array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        array([0, 1, 0, 0]), ..., 0.19246861924686165,
        0.13829063704375427, 0.512287334593573],
       [0.5185185185185184, array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
        array([0, 1, 0, 0]), ..., 0.19246861924686165,
        0.1632282929041034, 0.512287334593573],
       ...,
       [0.2222222222222222, array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        array([0, 1, 0, 0]), ..., 1.0, 0.027204715484017233,
        0.20378071833648193],
       [0.2839506172839506, array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]),
        array([0, 1, 0, 0]), ..., 0.6025104602510458, 0.9571525731126729,
        0.8597353497164448],
       [0.14814814814814814, array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        array([0, 0, 1, 0]), ..., 0.3389121338912131, 0.9807

In [320]:
x_train_l = x_train.tolist()

In [321]:
x_train_l

[[0.2839506172839506,
  array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
  array([0, 1, 0, 0]),
  array([0, 0, 1, 0, 0, 0, 0, 0]),
  array([0, 1, 0]),
  array([0, 0, 1]),
  array([1, 0, 0]),
  array([1]),
  array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
  array([0, 1, 0, 0, 0]),
  0.01818181818181818,
  0.0,
  array([0, 1, 0]),
  1.0,
  0.6691348402182271,
  0.3389121338912131,
  0.9807299931988211,
  1.0],
 [0.1728395061728395,
  array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
  array([0, 1, 0, 0]),
  array([0, 0, 0, 0, 0, 0, 1, 0]),
  array([1, 0, 0]),
  array([1, 0, 0]),
  array([1, 0, 0]),
  array([0]),
  array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
  array([0, 1, 0, 0, 0]),
  0.05454545454545454,
  0.0,
  array([0, 1, 0]),
  0.33333333333333337,
  0.269680436476996,
  0.19246861924686165,
  0.13829063704375427,
  0.512287334593573],
 [0.5185185185185184,
  array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
  array([0, 1, 0, 0]),
  array([1, 0, 0, 0, 0, 0, 0, 0]),
  array([1, 0, 0]),
  array([1, 0, 0]),
  ar

In [326]:
for t in x_train_l:
    for i in [1, 2, 3, 4, 5, 6, 7, 8, 9, 12]:
        t[i] = t[i].tolist()

In [327]:
x_train_l

[[0.2839506172839506,
  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 1, 0, 0],
  [0, 0, 1, 0, 0, 0, 0, 0],
  [0, 1, 0],
  [0, 0, 1],
  [1, 0, 0],
  [1],
  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
  [0, 1, 0, 0, 0],
  0.01818181818181818,
  0.0,
  [0, 1, 0],
  1.0,
  0.6691348402182271,
  0.3389121338912131,
  0.9807299931988211,
  1.0],
 [0.1728395061728395,
  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 1, 0, 0],
  [0, 0, 0, 0, 0, 0, 1, 0],
  [1, 0, 0],
  [1, 0, 0],
  [1, 0, 0],
  [0],
  [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
  [0, 1, 0, 0, 0],
  0.05454545454545454,
  0.0,
  [0, 1, 0],
  0.33333333333333337,
  0.269680436476996,
  0.19246861924686165,
  0.13829063704375427,
  0.512287334593573],
 [0.5185185185185184,
  [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
  [0, 1, 0, 0],
  [1, 0, 0, 0, 0, 0, 0, 0],
  [1, 0, 0],
  [1, 0, 0],
  [1, 0, 0],
  [0],
  [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
  [0, 1, 0, 0, 0],
  0.09090909090909091,
  0.14285714285714285,
  [1, 0, 0],
  0.33333333333333337,
  0.269680436476996,
  0

In [354]:
x_train_flat = []
for l in x_train_l:
    d = []
    for n in range(len(l)):
        if type(l[n]) != list :
            d.append(l[n])
        else :
            for k in range(len(l[n])):
                d.append(l[n][k])
    x_train_flat.append(d)

In [356]:
x_train = np.array(x_train_flat)

In [357]:
x_train.shape

(32950, 60)

In [329]:
y_train_l = y_train.tolist()

In [331]:
for t in y_train_l:
    t[0] = t[0].tolist()

In [334]:
y_train_l = np.array(y_train_l)

In [344]:
y_train=y_train_l.reshape(-1,1)

In [345]:
y_train

array([[0],
       [0],
       [0],
       ...,
       [1],
       [0],
       [0]])

In [346]:
y_train.shape

(32950, 1)

In [358]:
X = tf.placeholder(tf.float32, shape=[None,60])
Y = tf.placeholder(tf.float32, shape=[None,1])

In [359]:
W = tf.Variable(tf.random_normal([60,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [360]:
hypothesis = tf.sigmoid(tf.matmul(X,W)+b)
cost = -tf.reduce_mean(Y*tf.log(hypothesis)+(1-Y)*tf.log(1-hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [362]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(10001):
        cost_val, _ = sess.run([cost, train], feed_dict={X:x_train.astype(np.float32), Y:y_train.astype(np.float32)})
        if step % 200 == 0:
            print(step, cost_val)
            
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict={X:x_train, Y:y_train})
print("\nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)

0 0.5482869
200 0.4229909
400 0.40845412
600 0.40053758
800 0.39377192
1000 0.38759336
1200 0.3818956
1400 0.37662938
1600 0.37175375
1800 0.36723056
2000 0.36302844
2200 0.35911712
2400 0.35546994
2600 0.352063
2800 0.34887537
3000 0.34588826
3200 0.34308395
3400 0.34044793
3600 0.33796623
3800 0.33562654
4000 0.33341828
4200 0.33133098
4400 0.32935643
4600 0.32748547
4800 0.3257118
5000 0.324028
5200 0.32242918
5400 0.32090852
5600 0.31946132
5800 0.31808338
6000 0.31677055
6200 0.31551814
6400 0.3143232
6600 0.31318212
6800 0.31209153
7000 0.31104946
7200 0.31005183
7400 0.3090974
7600 0.30818343
7800 0.3073074
8000 0.30646816
8200 0.30566287
8400 0.3048904
8600 0.30414876
8800 0.3034359
9000 0.30275157
9200 0.30209336
9400 0.30146006
9600 0.3008511
9800 0.3002647
10000 0.29969963

Hypothesis:  [[0.01600215]
 [0.17476425]
 [0.09774995]
 ...
 [0.70969296]
 [0.05345928]
 [0.09160037]] 
Correct:  [[0.]
 [0.]
 [0.]
 ...
 [1.]
 [0.]
 [0.]] 
Accuracy:  0.8919272


In [363]:
test_set = test_set_noscale[:]

In [364]:
for i in range(len(scale_title)):
    test_set[scale_title[i]] = scaler_dic["scaler{0}".format(i)].transform(test_set[scale_title[i]])

/Users/freestylebk/anaconda/lib/python3.6/site-packages/sklearn/preprocessing/data.py:356: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/freestylebk/anaconda/lib/python3.6/site-packages/sklearn/preprocessing/data.py:356: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/freestylebk/anaconda/lib/python3.6/site-packages/sklearn/preprocessing/data.py:356: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.resha

In [366]:
len(test_set)

8238

In [367]:
test_set.head()

age                                   job       marital  \
32884  0.493827  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]  [0, 1, 0, 0]   
3169   0.469136  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]  [0, 1, 0, 0]   
32206  0.197531  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]  [0, 1, 0, 0]   
9403   0.234568  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]  [0, 1, 0, 0]   
14020  0.123457  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]  [0, 1, 0, 0]   

                      education    default    housing       loan contact  \
32884  [0, 0, 0, 1, 0, 0, 0, 0]  [1, 0, 0]  [1, 0, 0]  [0, 0, 1]     [0]   
3169   [0, 0, 0, 0, 0, 0, 0, 1]  [0, 1, 0]  [0, 0, 1]  [1, 0, 0]     [1]   
32206  [0, 0, 1, 0, 0, 0, 0, 0]  [1, 0, 0]  [1, 0, 0]  [1, 0, 0]     [0]   
9403   [0, 0, 0, 1, 0, 0, 0, 0]  [1, 0, 0]  [1, 0, 0]  [1, 0, 0]     [1]   
14020  [0, 0, 0, 1, 0, 0, 0, 0]  [1, 0, 0]  [0, 0, 1]  [1, 0, 0]     [0]   

                                month      day_of_week  campaign  previous  \
32884  [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]  [0, 1, 0, 0, 0]  0.000000  0.142857   
3169   [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]  [0, 0, 1, 0, 0]  0.018182  0.000000   
32206  [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]  [1, 0, 0, 0, 0]  0.000000  0.142857   
9403   [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]  [1, 0, 0, 0, 0]  0.054545  0.000000   
14020  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0]  [1, 0, 0, 0, 0]  0.018182  0.000000   

        poutcome  emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
32884  [1, 0, 0]      0.333333        0.269680       0.192469   0.150759   
3169   [0, 1, 0]      0.937500        0.698753       0.602510   0.958059   
32206  [1, 0, 0]      0.333333        0.269680       0.192469   0.153933   
9403   [0, 1, 0]      1.000000        0.882307       0.376569   0.982317   
14020  [0, 1, 0]      1.000000        0.669135       0.338912   0.981410   

       nr.employed    y  
32884     0.512287  [0]  
3169      0.859735  [0]  
32206     0.512287  [0]  
9403      1.000000  [0]  
14020     1.000000  [0]

In [368]:
test_set.values

array([[0.4938271604938272, list([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
        list([0, 1, 0, 0]), ..., 0.15075946497392884, 0.512287334593573,
        list([0])],
       [0.4691358024691357, list([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
        list([0, 1, 0, 0]), ..., 0.9580593969621403, 0.8597353497164448,
        list([0])],
       [0.19753086419753085, list([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        list([0, 1, 0, 0]), ..., 0.1539333484470642, 0.512287334593573,
        list([0])],
       ...,
       [0.35802469135802467, list([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        list([0, 0, 1, 0]), ..., 0.17479029698481074, 0.512287334593573,
        list([0])],
       [0.1728395061728395, list([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        list([0, 0, 1, 0]), ..., 0.9814101110859217, 1.0, list([1])],
       [0.5185185185185184, list([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        list([0, 1, 0, 0]), ..., 0.9569258671503063, 0.8597353497164448,
        list([0])]], dtype=object)

In [369]:
for t in dftitle:
    test_set[t] = test_set[t].apply(lambda x:np.array(x))

In [370]:
test_set.values

array([[0.4938271604938272, array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
        list([0, 1, 0, 0]), ..., 0.15075946497392884, 0.512287334593573,
        array([0])],
       [0.4691358024691357, array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
        list([0, 1, 0, 0]), ..., 0.9580593969621403, 0.8597353497164448,
        array([0])],
       [0.19753086419753085, array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        list([0, 1, 0, 0]), ..., 0.1539333484470642, 0.512287334593573,
        array([0])],
       ...,
       [0.35802469135802467, array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        list([0, 0, 1, 0]), ..., 0.17479029698481074, 0.512287334593573,
        array([0])],
       [0.1728395061728395, array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        list([0, 0, 1, 0]), ..., 0.9814101110859217, 1.0, array([1])],
       [0.5185185185185184, array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        list([0, 1, 0, 0]), ..., 0.9569258671503063, 0.8597353497164448,
        array([0])]], dtype=o

In [371]:
test_set['marital'] = test_set['marital'].apply(lambda x:np.array(x))

In [372]:
test_set.values

array([[0.4938271604938272, array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
        array([0, 1, 0, 0]), ..., 0.15075946497392884, 0.512287334593573,
        array([0])],
       [0.4691358024691357, array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
        array([0, 1, 0, 0]), ..., 0.9580593969621403, 0.8597353497164448,
        array([0])],
       [0.19753086419753085, array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        array([0, 1, 0, 0]), ..., 0.1539333484470642, 0.512287334593573,
        array([0])],
       ...,
       [0.35802469135802467, array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        array([0, 0, 1, 0]), ..., 0.17479029698481074, 0.512287334593573,
        array([0])],
       [0.1728395061728395, array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        array([0, 0, 1, 0]), ..., 0.9814101110859217, 1.0, array([1])],
       [0.5185185185185184, array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        array([0, 1, 0, 0]), ..., 0.9569258671503063, 0.8597353497164448,
        array([0])]], d

In [373]:
x_test = test_set.values[:,0:-1]
y_test = test_set.values[:,[-1]]

In [374]:
x_test_l = x_test.tolist()
for t in x_test_l:
    for i in [1, 2, 3, 4, 5, 6, 7, 8, 9, 12]:
        t[i] = t[i].tolist()

x_test_flat = []
for l in x_test_l:
    d = []
    for n in range(len(l)):
        if type(l[n]) != list :
            d.append(l[n])
        else :
            for k in range(len(l[n])):
                d.append(l[n][k])
    x_test_flat.append(d)

In [376]:
x_test = np.array(x_test_flat)

In [377]:
x_test.shape

(8238, 60)

In [378]:
y_test_l = y_test.tolist()
for t in y_test_l:
    t[0] = t[0].tolist()
    
y_test_l = np.array(y_test_l)
y_test=y_test_l.reshape(-1,1)

In [379]:
y_test.shape

(8238, 1)

In [384]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(1001):
        cost_val, _ = sess.run([cost, train], feed_dict={X:x_train.astype(np.float32), Y:y_train.astype(np.float32)})
        if step % 200 == 0:
            print(step, cost_val)
            
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict={X:x_train, Y:y_train})
    h_t, c_t, a_t = sess.run([hypothesis, predicted, accuracy], feed_dict={X:x_test, Y:y_test})
print("trainset result: \nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)
print("testset result: \nHypothesis: ", h_t, "\nCorrect: ", c_t, "\nAccuracy: ", a_t)

0 1.8528526
200 0.52917266
400 0.4662173
600 0.45109725
800 0.44157824
1000 0.43329886
trainset result: 
Hypothesis:  [[0.17214997]
 [0.0275843 ]
 [0.15979907]
 ...
 [0.90248686]
 [0.0082044 ]
 [0.15550064]] 
Correct:  [[0.]
 [0.]
 [0.]
 ...
 [1.]
 [0.]
 [0.]] 
Accuracy:  0.86403644
testset result: 
Hypothesis:  [[0.5437545 ]
 [0.0133668 ]
 [0.07874928]
 ...
 [0.8551325 ]
 [0.04318238]
 [0.03907074]] 
Correct:  [[1.]
 [0.]
 [0.]
 ...
 [1.]
 [0.]
 [0.]] 
Accuracy:  0.8606458
