In [1]:
import tensorflow as tf
import numpy as np
import matplotlib
import os

/Users/freestylebk/anaconda/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
tf.set_random_seed(777)

In [4]:
if 'DISPLAY' not in os.environ:
    matplotlib.use('Agg')

In [5]:
import matplotlib.pyplot as plt

In [6]:
def MinMaxScaler(data):
    numerator = data-np.min(data,0)
    denominator = np.max(data, 0) - np.min(data, 0)
    return numerator / (denominator + 1e-7)

In [7]:
seq_length = 7
data_dim = 5
hidden_dim = 10
output_dim = 1
learning_rate = 0.01
iterations = 500

In [9]:
xy = np.loadtxt('data-stock-daily.csv', delimiter=',')

In [11]:
# xy = xy[::-1] -> 역순으로 데이터를 정렬해주고 싶을 때
xy = MinMaxScaler(xy)
x = xy
y = xy[:, [-1]]

In [12]:
dataX = []
dataY = []
for i in range(0, len(y)-seq_length):
    _x = x[i:i+seq_length]
    _y = y[i+seq_length]
    print(_x, "->", _y)
    dataX.append(_x)
    dataY.append(_y)

[[0.04322499 0.04677871 0.04237483 0.10470308 0.05257159]
 [0.04437401 0.04221161 0.04540326 0.11995074 0.04703313]
 [0.0455683  0.05116623 0.043889   0.15069047 0.06010205]
 [0.05598482 0.05269359 0.0577364  0.06299294 0.05782332]
 [0.05940154 0.05407125 0.06213515 0.19644284 0.06139998]
 [0.05755711 0.05502957 0.0572594  0.10367843 0.05906076]
 [0.06077732 0.07334317 0.06540584 0.19328426 0.07623463]] -> [0.05902307]
[[0.04437401 0.04221161 0.04540326 0.11995074 0.04703313]
 [0.0455683  0.05116623 0.043889   0.15069047 0.06010205]
 [0.05598482 0.05269359 0.0577364  0.06299294 0.05782332]
 [0.05940154 0.05407125 0.06213515 0.19644284 0.06139998]
 [0.05755711 0.05502957 0.0572594  0.10367843 0.05906076]
 [0.06077732 0.07334317 0.06540584 0.19328426 0.07623463]
 [0.07278125 0.06985413 0.06166577 0.15276799 0.05902307]] -> [0.05356759]
[[0.0455683  0.05116623 0.043889   0.15069047 0.06010205]
 [0.05598482 0.05269359 0.0577364  0.06299294 0.05782332]
 [0.05940154 0.05407125 0.06213515 0.1

 [0.00235621 0.         0.00141594 0.07233707 0.        ]] -> [0.00584206]
[[0.00991141 0.00529392 0.00809989 0.16059863 0.00558412]
 [0.00795035 0.00445075 0.00464371 0.13478477 0.00760233]
 [0.00240186 0.00288489 0.00898298 0.06662154 0.00996951]
 [0.         0.00378825 0.00581609 0.07081418 0.00915004]
 [0.00551815 0.00518852 0.         0.10058565 0.01242774]
 [0.00235621 0.         0.00141594 0.07233707 0.        ]
 [0.00550293 0.00155989 0.00787147 0.12362635 0.00584206]] -> [0.02018177]
[[0.00795035 0.00445075 0.00464371 0.13478477 0.00760233]
 [0.00240186 0.00288489 0.00898298 0.06662154 0.00996951]
 [0.         0.00378825 0.00581609 0.07081418 0.00915004]
 [0.00551815 0.00518852 0.         0.10058565 0.01242774]
 [0.00235621 0.         0.00141594 0.07233707 0.        ]
 [0.00550293 0.00155989 0.00787147 0.12362635 0.00584206]
 [0.01032178 0.0147947  0.01578867 0.13438055 0.02018177]] -> [0.04509791]
[[0.00240186 0.00288489 0.00898298 0.06662154 0.00996951]
 [0.         0.003788

 [0.36927474 0.36127955 0.3559988  0.09646822 0.35295366]] -> [0.3375973]
[[0.35472689 0.3509958  0.34812733 0.1370315  0.35299923]
 [0.33695634 0.33572837 0.33734776 0.15954577 0.33692963]
 [0.33791404 0.34027543 0.31819427 0.17722816 0.35043477]
 [0.35495495 0.3543535  0.34687884 0.2010773  0.34380362]
 [0.3503945  0.35813275 0.34143576 0.13782115 0.36609464]
 [0.36927474 0.36127955 0.3559988  0.09646822 0.35295366]
 [0.3450892  0.34840609 0.33947935 0.24643485 0.3375973 ]] -> [0.35043477]
[[0.33695634 0.33572837 0.33734776 0.15954577 0.33692963]
 [0.33791404 0.34027543 0.31819427 0.17722816 0.35043477]
 [0.35495495 0.3543535  0.34687884 0.2010773  0.34380362]
 [0.3503945  0.35813275 0.34143576 0.13782115 0.36609464]
 [0.36927474 0.36127955 0.3559988  0.09646822 0.35295366]
 [0.3450892  0.34840609 0.33947935 0.24643485 0.3375973 ]
 [0.34451153 0.34218766 0.342296   0.09386428 0.35043477]] -> [0.35381861]
[[0.33791404 0.34027543 0.31819427 0.17722816 0.35043477]
 [0.35495495 0.3543535

 [0.38537316 0.37820327 0.38555113 0.05127988 0.38638264]] -> [0.39946286]
[[0.37927735 0.38145557 0.38165345 0.06011638 0.38346911]
 [0.37888209 0.37981435 0.38281821 0.02949886 0.38742967]
 [0.37977902 0.3790254  0.38316084 0.05666638 0.38278635]
 [0.37625226 0.37093095 0.38093791 0.06781541 0.37969073]
 [0.37965738 0.37383688 0.37929354 0.0374047  0.38231595]
 [0.38537316 0.37820327 0.38555113 0.05127988 0.38638264]
 [0.38604203 0.39036911 0.38949454 0.08607124 0.39946286]] -> [0.3998725]
[[0.37888209 0.37981435 0.38281821 0.02949886 0.38742967]
 [0.37977902 0.3790254  0.38316084 0.05666638 0.38278635]
 [0.37625226 0.37093095 0.38093791 0.06781541 0.37969073]
 [0.37965738 0.37383688 0.37929354 0.0374047  0.38231595]
 [0.38537316 0.37820327 0.38555113 0.05127988 0.38638264]
 [0.38604203 0.39036911 0.38949454 0.08607124 0.39946286]
 [0.39599899 0.39146822 0.39741173 0.03445294 0.3998725 ]] -> [0.39223989]
[[0.37977902 0.3790254  0.38316084 0.05666638 0.38278635]
 [0.37625226 0.3709309

In [13]:
train_size = int(len(dataY)*0.7)
test_size = len(dataY)-train_size
trainX, testX = np.array(dataX[0:train_size]), np.array(dataX[train_size:len(dataX)])
trainY, testY = np.array(dataY[0:train_size]), np.array(dataY[train_size:len(dataY)])

In [14]:
X = tf.placeholder(tf.float32, [None, seq_length, data_dim])
Y = tf.placeholder(tf.float32, [None, 1])

In [15]:
cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_dim, state_is_tuple=True, activation=tf.tanh)
outputs, _states = tf.nn.dynamic_rnn(cell, X, dtype=tf.float32)
Y_pred = tf.contrib.layers.fully_connected(outputs[:, -1], output_dim, activation_fn=None)

In [17]:
loss = tf.reduce_sum(tf.square(Y_pred-Y))
optimizer = tf.train.AdamOptimizer(learning_rate)
train = optimizer.minimize(loss)

In [18]:
targets = tf.placeholder(tf.float32, [None, 1])
predictions = tf.placeholder(tf.float32, [None, 1])
rmse = tf.sqrt(tf.reduce_mean(tf.square(targets-predictions)))

In [26]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    
    for i in range(iterations):
        _, step_loss = sess.run([train, loss], feed_dict={X: trainX, Y:trainY})
        print("[step:{}] loss: {}".format(i, step_loss))
        
    test_predict = sess.run(Y_pred, feed_dict={X:testX})
    rmse_val = sess.run(rmse, feed_dict={targets:testY, predictions:test_predict})
    print("RMSE: {}".format(rmse_val))
    
    plt.plot(testY)
    plt.plot(test_predict)
    plt.xlabel("Time Period")
    plt.ylabel("Stock Price")
    plt.savefig('stock-prediction.png')

[step:0] loss: 99.11125946044922
[step:1] loss: 59.13701629638672
[step:2] loss: 30.56740379333496
[step:3] loss: 12.616901397705078
[step:4] loss: 4.801023960113525
[step:5] loss: 6.16196346282959
[step:6] loss: 12.392426490783691
[step:7] loss: 16.451642990112305
[step:8] loss: 16.114126205444336
[step:9] loss: 12.924650192260742
[step:10] loss: 8.989089012145996
[step:11] loss: 5.730510711669922
[step:12] loss: 3.7382771968841553
[step:13] loss: 2.9983344078063965
[step:14] loss: 3.1800994873046875
[step:15] loss: 3.8547847270965576
[step:16] loss: 4.633307456970215
[step:17] loss: 5.240706920623779
[step:18] loss: 5.533487796783447
[step:19] loss: 5.478310585021973
[step:20] loss: 5.1174397468566895
[step:21] loss: 4.536517143249512
[step:22] loss: 3.8394792079925537
[step:23] loss: 3.1301774978637695
[step:24] loss: 2.498953342437744
[step:25] loss: 2.0125997066497803
[step:26] loss: 1.7071096897125244
[step:27] loss: 1.5837340354919434
[step:28] loss: 1.6098393201828003
[step:29]

[step:244] loss: 0.23606708645820618
[step:245] loss: 0.23591332137584686
[step:246] loss: 0.23575972020626068
[step:247] loss: 0.2356060892343521
[step:248] loss: 0.23545251786708832
[step:249] loss: 0.2352990061044693
[step:250] loss: 0.23514552414417267
[step:251] loss: 0.23499207198619843
[step:252] loss: 0.23483863472938538
[step:253] loss: 0.2346852868795395
[step:254] loss: 0.23453199863433838
[step:255] loss: 0.23437872529029846
[step:256] loss: 0.23422552645206451
[step:257] loss: 0.23407229781150818
[step:258] loss: 0.23391923308372498
[step:259] loss: 0.23376615345478058
[step:260] loss: 0.23361308872699738
[step:261] loss: 0.23346014320850372
[step:262] loss: 0.23330718278884888
[step:263] loss: 0.23315438628196716
[step:264] loss: 0.2330014705657959
[step:265] loss: 0.23284870386123657
[step:266] loss: 0.2326960563659668
[step:267] loss: 0.23254340887069702
[step:268] loss: 0.23239079117774963
[step:269] loss: 0.23223821818828583
[step:270] loss: 0.2320856899023056
[step:2

[step:474] loss: 0.20291399955749512
[step:475] loss: 0.20278343558311462
[step:476] loss: 0.20265299081802368
[step:477] loss: 0.20252273976802826
[step:478] loss: 0.2023925483226776
[step:479] loss: 0.2022625058889389
[step:480] loss: 0.20213262736797333
[step:481] loss: 0.20200291275978088
[step:482] loss: 0.2018733024597168
[step:483] loss: 0.20174387097358704
[step:484] loss: 0.2016145884990692
[step:485] loss: 0.20148539543151855
[step:486] loss: 0.20135638117790222
[step:487] loss: 0.20122750103473663
[step:488] loss: 0.20109869539737701
[step:489] loss: 0.2009701430797577
[step:490] loss: 0.20084165036678314
[step:491] loss: 0.2007133960723877
[step:492] loss: 0.20058515667915344
[step:493] loss: 0.20045720040798187
[step:494] loss: 0.20032931864261627
[step:495] loss: 0.20020154118537903
[step:496] loss: 0.2000739425420761
[step:497] loss: 0.1999465376138687
[step:498] loss: 0.19981922209262848
[step:499] loss: 0.19969205558300018
RMSE: 0.07545590400695801
